# Generated by Django 4.2.6 on 2023-10-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
