# Generated by Django 4.2.6 on 2023-10-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_ad_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='default',
        ),
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
