# Generated by Django 4.2.6 on 2023-10-18 08:22

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_remove_media_default_alter_media_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='embed_video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
