# Generated by Django 4.2.6 on 2023-10-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_alter_ad_ad_title_alter_ad_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='ad_text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='ad_title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_text',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
