# Generated by Django 4.2.6 on 2023-10-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0011_alter_ad_ad_text_alter_ad_ad_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='is_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
