# Generated by Django 4.2.6 on 2023-10-21 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0012_reply_is_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.ad', verbose_name='Объявление'),
        ),
    ]
