# Generated by Django 4.2.6 on 2023-10-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0014_alter_reply_is_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='is_confirm',
            field=models.CharField(choices=[('true', 'Принят'), ('false', 'Не принят')], default='false', max_length=15, verbose_name='Статус'),
        ),
    ]
