# Generated by Django 4.2.6 on 2023-10-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0016_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение'),
        ),
    ]
